name: Test

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - run: npm ci
      - run: |
          npx jest --coverage --no-color 2>&1 | tee $GITHUB_STEP_SUMMARY
          exit_code=${PIPESTATUS[0]}
          exit $exit_code
